name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/verify

      - name: Lint
        run: npm run lint

      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium

      - name: E2E
        run: npm run e2e
